### ISSUE TITLE
Get variables of active theme

### ISSUE THREAD

**Issue by gcushen** [brunolemos/react-theme-manager#2]
Great work with this new project!

I think it is quite common to want to access the global variables directly, not only indirectly via the derived style sheet. This is especially true when styling third party package components via custom props, or when using small snippets of in-line styling. As far as I can see, there is currently no built-in method to achieve this. For example, say you have:

```
const darkThemeVariables = { primary: '#333333'}; 
const lightThemeVariables = { primary: '#eeeeee'};
ThemeManager.addVariables('dark', darkThemeVariables);
ThemeManager.addVariables('light', lightThemeVariables);
```

Then something like the following would be very useful:

```
let activeThemeVars = ThemeManager.getVariables(this.context.theme)
let activePrimaryColor = activeThemeVars.primary
```

Such that `'#333333'` would be set as the `activePrimaryColor`variable if the Dark theme is active.

**Comment by brunolemos** [comment]
Thanks @gcushen !

There is currently a `getVariable` method to get a single variable:
`console.log('variable', ThemeManager.getVariable('dark', 'primary'));`

If you need to get all variables, try this:
`console.log('current theme variables', ThemeManager.themeVariables['dark']);`
But that may change, I'll add a `getVariables` method in the next version.

Please let me know if that works.

**Comment by gcushen** [comment]
Thank you very much for the fast reply @brunolemos !

Those two methods/objects that you mentioned are very useful. I just tested them both in my app and they solve my advanced theming problems.

Yes, `getVariables` sounds like a good method name to compliment your existing `getVariable` method :smiley:

**Comment by brunolemos** [comment]
@gcushen Great! 🎉
